### ISSUE TITLE
Judge setup error

### ISSUE THREAD

**Issue by duongnotnhan** [VNOI-Admin/judge-server#34]
sudo make judge-tier1
[sudo] password for duongnhanac: 

```
docker build --build-arg TAG="master" -t vnoj/judge-tier1 -t vnoj/judge-tier1:latest tier1
[+] Building 19.7s (7/7) FINISHED                  docker:default
 => [internal] load build definition from Dockerfile         0.0s
 => => transferring dockerfile: 1.71kB                       0.0s
 => [internal] load .dockerignore                            0.0s
 => => transferring context: 2B                              0.0s
 => [internal] load metadata for docker.io/dmoj/runtimes-ti  3.1s
 => [1/4] FROM docker.io/dmoj/runtimes-tier1@sha256:5f76244  0.0s
 => CACHED [2/4] RUN apt-get update &&  apt-get install -y   0.0s
 => CACHED [3/4] RUN ARCH=$([ $(uname -m) = "x86_64" ] && e  0.0s
 => ERROR [4/4] RUN mkdir /judge /problems && cd /judge &&  16.5s
------                                                            
 > [4/4] RUN mkdir /judge /problems && cd /judge &&     curl -L https://github.com/VNOI-Admin/judge-server/archive/"master".tar.gz | tar -xz --strip-components=1 &&        python3 -m venv --prompt=DMOJ /env &&     /env/bin/pip3 install cython &&         /env/bin/pip3 install -e . &&     /env/bin/python3 setup.py develop &&    HOME=~judge . ~judge/.profile && 	runuser -u judge -w PATH -- /env/bin/dmoj-autoconf -V > /judge-runtime-paths.yml && 	echo '  crt_x86_in_lib32: true' >> /judge-runtime-paths.yml && 	curl -L https://raw.githubusercontent.com/VNOI-Admin/testlib/master/testlib.h -o /usr/include/testlib.h && 	g++ -std=c++17 -Wall -DONLINE_JUDGE -O2 -fmax-errors=5 -march=native -s /usr/include/testlib.h && 	curl -L https://raw.githubusercontent.com/skyvn97/testlib/customized-testlib/testlib_themis_cms.h -o /usr/include/testlib_themis_cms.h && 	g++ -std=c++17 -Wall -DONLINE_JUDGE -DTHEMIS -O2 -fmax-errors=5 -march=native -s /usr/include/testlib_themis_cms.h && 	find /usr/include/ -name stdc++.h -exec g++ -std=c++17 -Wall -DONLINE_JUDGE -O2 -fmax-errors=5 -march=native -s {} ;:
0.435   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
0.435                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 15749    0 15749    0     0  10217      0 --:--:--  0:00:01 --100  492k    0  492k    0     0   200k      0 --:--:--  0:00:02 --100  977k    0  977k    0     0   375k      0 --:--:--  0:00:02 --:--:--  904k
8.673 Collecting cython
8.909   Downloading Cython-3.0.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
9.422      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 7.1 MB/s eta 0:00:00
9.493 Installing collected packages: cython
10.34 Successfully installed cython-3.0.0
10.85 Obtaining file:///judge
10.85   Installing build dependencies: started
14.97   Installing build dependencies: finished with status 'done'
15.02   Checking if build backend supports build_editable: started
15.18   Checking if build backend supports build_editable: finished with status 'done'
15.18   Getting requirements to build editable: started
16.27   Getting requirements to build editable: finished with status 'error'
16.28   error: subprocess-exited-with-error
16.28   
16.28   × Getting requirements to build editable did not run successfully.
16.28   │ exit code: 1
16.28   ╰─> [86 lines of output]
16.28       
16.28       Error compiling Cython file:
16.28       ------------------------------------------------------------
16.28       ...
16.28           def abi(self):
16.28               return self.thisptr.abi()
16.28       
16.28           def on_return(self, callback):
16.28               self.on_return_callback[self.tid] = callback
16.28               self.thisptr.on_return(pt_syscall_return_handler, <void*>self)
16.28                                      ^
16.28       ------------------------------------------------------------
16.28       
16.28       dmoj/cptbox/_cptbox.pyx:414:31: Cannot assign type 'void (void *, pid_t, int) except * nogil' to 'pt_syscall_return_callback'
16.28       
16.28       Error compiling Cython file:
16.28       ------------------------------------------------------------
16.28       ...
16.28               self._cpu_affinity_mask = 0
16.28               self._init_nvcsw = self._init_nivcsw = 0
16.28       
16.28               self.debugger = self.create_debugger()
16.28               self.process = new pt_process(self.debugger.thisptr)
16.28               self.process.set_callback(pt_syscall_handler, <void*>self)
16.28                                         ^
16.28       ------------------------------------------------------------
16.28       
16.28       dmoj/cptbox/_cptbox.pyx:448:34: Cannot assign type 'int (void *, int) except? -1 nogil' to 'pt_handler_callback'
16.28       
16.28       Error compiling Cython file:
16.28       ------------------------------------------------------------
16.28       ...
16.28               self._init_nvcsw = self._init_nivcsw = 0
16.28       
16.28               self.debugger = self.create_debugger()
16.28               self.process = new pt_process(self.debugger.thisptr)
16.28               self.process.set_callback(pt_syscall_handler, <void*>self)
16.28               self.process.set_event_proc(pt_event_handler, <void*>self)
16.28                                           ^
16.28       ------------------------------------------------------------
16.28       
16.28       dmoj/cptbox/_cptbox.pyx:449:36: Cannot assign type 'int (void *, int, unsigned long) except? -1 nogil' to 'pt_event_callback'
16.28       
16.28       Error compiling Cython file:
16.28       ------------------------------------------------------------
16.28       ...
16.28                           PyErr_NoMemory()
16.28       
16.28                       for i in range(MAX_SYSCALL):
16.28                           config.seccomp_handlers[i] = handlers[i]
16.28       
16.28                   if self.process.spawn(pt_child, &config):
16.28                                         ^
16.28       ------------------------------------------------------------
16.28       
16.28       dmoj/cptbox/_cptbox.pyx:534:34: Cannot assign type 'int (void *) except? -1 nogil' to 'pt_fork_handler'
16.28       Compiling /judge/dmoj/cptbox/_cptbox.pyx because it changed.
16.28       [1/1] Cythonizing /judge/dmoj/cptbox/_cptbox.pyx
16.28       Traceback (most recent call last):
16.28         File "/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
16.28           main()
16.28         File "/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
16.28           json_out['return_val'] = hook(**hook_input['kwargs'])
16.28                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16.28         File "/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
16.28           return hook(config_settings)
16.28                  ^^^^^^^^^^^^^^^^^^^^^
16.28         File "/tmp/pip-build-env-p_4pshls/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 450, in get_requires_for_build_editable
16.28           return self.get_requires_for_build_wheel(config_settings)
16.28                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16.28         File "/tmp/pip-build-env-p_4pshls/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
16.28           return self._get_build_requires(config_settings, requirements=['wheel'])
16.28                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16.28         File "/tmp/pip-build-env-p_4pshls/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
16.28           self.run_setup()
16.28         File "/tmp/pip-build-env-p_4pshls/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
16.28           self).run_setup(setup_script=setup_script)
16.28                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16.28         File "/tmp/pip-build-env-p_4pshls/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
16.28           exec(code, locals())
16.28         File "<string>", line 177, in <module>
16.28         File "/tmp/pip-build-env-p_4pshls/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
16.28           cythonize_one(*args)
16.28         File "/tmp/pip-build-env-p_4pshls/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
16.28           raise CompileError(None, pyx_file)
16.28       Cython.Compiler.Errors.CompileError: /judge/dmoj/cptbox/_cptbox.pyx
16.28       [end of output]
16.28   
16.28   note: This error originates from a subprocess, and is likely not a problem with pip.
16.28 error: subprocess-exited-with-error
16.28 
16.28 × Getting requirements to build editable did not run successfully.
16.28 │ exit code: 1
16.28 ╰─> See above for output.
16.28 
16.28 note: This error originates from a subprocess, and is likely not a problem with pip.
------
Dockerfile:16
--------------------
  15 |     
  16 | >>> RUN mkdir /judge /problems && cd /judge && \
  17 | >>> 	curl -L https://github.com/VNOI-Admin/judge-server/archive/"${TAG}".tar.gz | tar -xz --strip-components=1 && \
  18 | >>> 	python3 -m venv --prompt=DMOJ /env && \
  19 | >>> 	/env/bin/pip3 install cython && \
  20 | >>> 	/env/bin/pip3 install -e . && \
  21 | >>> 	/env/bin/python3 setup.py develop && \
  22 | >>> 	HOME=~judge . ~judge/.profile && \
  23 | >>> 	runuser -u judge -w PATH -- /env/bin/dmoj-autoconf -V > /judge-runtime-paths.yml && \
  24 | >>> 	echo '  crt_x86_in_lib32: true' >> /judge-runtime-paths.yml && \
  25 | >>> 	curl -L https://raw.githubusercontent.com/VNOI-Admin/testlib/master/testlib.h -o /usr/include/testlib.h && \
  26 | >>> 	g++ -std=c++17 -Wall -DONLINE_JUDGE -O2 -fmax-errors=5 -march=native -s /usr/include/testlib.h && \
  27 | >>> 	curl -L https://raw.githubusercontent.com/skyvn97/testlib/customized-testlib/testlib_themis_cms.h -o /usr/include/testlib_themis_cms.h && \
  28 | >>> 	g++ -std=c++17 -Wall -DONLINE_JUDGE -DTHEMIS -O2 -fmax-errors=5 -march=native -s /usr/include/testlib_themis_cms.h && \
  29 | >>> 	find /usr/include/ -name stdc++.h -exec g++ -std=c++17 -Wall -DONLINE_JUDGE -O2 -fmax-errors=5 -march=native -s {} \;
  30 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c mkdir /judge /problems && cd /judge && \tcurl -L https://github.com/VNOI-Admin/judge-server/archive/\"${TAG}\".tar.gz | tar -xz --strip-components=1 && \tpython3 -m venv --prompt=DMOJ /env && \t/env/bin/pip3 install cython && \t/env/bin/pip3 install -e . && \t/env/bin/python3 setup.py develop && \tHOME=~judge . ~judge/.profile && \trunuser -u judge -w PATH -- /env/bin/dmoj-autoconf -V > /judge-runtime-paths.yml && \techo '  crt_x86_in_lib32: true' >> /judge-runtime-paths.yml && \tcurl -L https://raw.githubusercontent.com/VNOI-Admin/testlib/master/testlib.h -o /usr/include/testlib.h && \tg++ -std=c++17 -Wall -DONLINE_JUDGE -O2 -fmax-errors=5 -march=native -s /usr/include/testlib.h && \tcurl -L https://raw.githubusercontent.com/skyvn97/testlib/customized-testlib/testlib_themis_cms.h -o /usr/include/testlib_themis_cms.h && \tg++ -std=c++17 -Wall -DONLINE_JUDGE -DTHEMIS -O2 -fmax-errors=5 -march=native -s /usr/include/testlib_themis_cms.h && \tfind /usr/include/ -name stdc++.h -exec g++ -std=c++17 -Wall -DONLINE_JUDGE -O2 -fmax-errors=5 -march=native -s {} \\;" did not complete successfully: exit code: 1
make: *** [Makefile:9: judge-tier1] Error 1
```

**Comment by hieplpvip** [comment]
Fixed in https://github.com/VNOI-Admin/judge-server/commit/3a224a3f0ee4f876049a1e0ee2e42829b9608e05
